
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file should be your main import to use Prisma-related types and utilities in a browser. 
 * Use it to get access to models, enums, and input types.
 * 
 * This file does not contain a `PrismaClient` class, nor several other helpers that are intended as server-side only.
 * See `client.ts` for the standard, server-side entry point.
 *
 * 🟢 You can import this file directly.
 */

import * as Prisma from './internal/prismaNamespaceBrowser'
export { Prisma }
export * as $Enums from './enums'
export * from './enums';
/**
 * Model User
 * 
 */
export type User = Prisma.UserModel
/**
 * Model Contest
 * 
 */
export type Contest = Prisma.ContestModel
/**
 * Model Question
 * 
 */
export type Question = Prisma.QuestionModel
/**
 * Model Option
 * 
 */
export type Option = Prisma.OptionModel
/**
 * Model Participation
 * 
 */
export type Participation = Prisma.ParticipationModel
/**
 * Model Answer
 * 
 */
export type Answer = Prisma.AnswerModel
/**
 * Model LeaderboardEntry
 * 
 */
export type LeaderboardEntry = Prisma.LeaderboardEntryModel
/**
 * Model PrizeAwarded
 * 
 */
export type PrizeAwarded = Prisma.PrizeAwardedModel
