
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This is a barrel export file for all models and their related types.
 *
 * 🟢 You can import this file directly.
 */
export type * from './models/User'
export type * from './models/Contest'
export type * from './models/Question'
export type * from './models/Option'
export type * from './models/Participation'
export type * from './models/Answer'
export type * from './models/LeaderboardEntry'
export type * from './models/PrizeAwarded'
export type * from './commonInputTypes'