
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `LeaderboardEntry` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model LeaderboardEntry
 * 
 */
export type LeaderboardEntryModel = runtime.Types.Result.DefaultSelection<Prisma.$LeaderboardEntryPayload>

export type AggregateLeaderboardEntry = {
  _count: LeaderboardEntryCountAggregateOutputType | null
  _avg: LeaderboardEntryAvgAggregateOutputType | null
  _sum: LeaderboardEntrySumAggregateOutputType | null
  _min: LeaderboardEntryMinAggregateOutputType | null
  _max: LeaderboardEntryMaxAggregateOutputType | null
}

export type LeaderboardEntryAvgAggregateOutputType = {
  score: number | null
  rank: number | null
}

export type LeaderboardEntrySumAggregateOutputType = {
  score: number | null
  rank: number | null
}

export type LeaderboardEntryMinAggregateOutputType = {
  id: string | null
  contestId: string | null
  userId: string | null
  score: number | null
  rank: number | null
  updatedAt: Date | null
}

export type LeaderboardEntryMaxAggregateOutputType = {
  id: string | null
  contestId: string | null
  userId: string | null
  score: number | null
  rank: number | null
  updatedAt: Date | null
}

export type LeaderboardEntryCountAggregateOutputType = {
  id: number
  contestId: number
  userId: number
  score: number
  rank: number
  updatedAt: number
  _all: number
}


export type LeaderboardEntryAvgAggregateInputType = {
  score?: true
  rank?: true
}

export type LeaderboardEntrySumAggregateInputType = {
  score?: true
  rank?: true
}

export type LeaderboardEntryMinAggregateInputType = {
  id?: true
  contestId?: true
  userId?: true
  score?: true
  rank?: true
  updatedAt?: true
}

export type LeaderboardEntryMaxAggregateInputType = {
  id?: true
  contestId?: true
  userId?: true
  score?: true
  rank?: true
  updatedAt?: true
}

export type LeaderboardEntryCountAggregateInputType = {
  id?: true
  contestId?: true
  userId?: true
  score?: true
  rank?: true
  updatedAt?: true
  _all?: true
}

export type LeaderboardEntryAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LeaderboardEntry to aggregate.
   */
  where?: Prisma.LeaderboardEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaderboardEntries to fetch.
   */
  orderBy?: Prisma.LeaderboardEntryOrderByWithRelationInput | Prisma.LeaderboardEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.LeaderboardEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaderboardEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaderboardEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned LeaderboardEntries
  **/
  _count?: true | LeaderboardEntryCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: LeaderboardEntryAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: LeaderboardEntrySumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: LeaderboardEntryMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: LeaderboardEntryMaxAggregateInputType
}

export type GetLeaderboardEntryAggregateType<T extends LeaderboardEntryAggregateArgs> = {
      [P in keyof T & keyof AggregateLeaderboardEntry]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateLeaderboardEntry[P]>
    : Prisma.GetScalarType<T[P], AggregateLeaderboardEntry[P]>
}




export type LeaderboardEntryGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.LeaderboardEntryWhereInput
  orderBy?: Prisma.LeaderboardEntryOrderByWithAggregationInput | Prisma.LeaderboardEntryOrderByWithAggregationInput[]
  by: Prisma.LeaderboardEntryScalarFieldEnum[] | Prisma.LeaderboardEntryScalarFieldEnum
  having?: Prisma.LeaderboardEntryScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: LeaderboardEntryCountAggregateInputType | true
  _avg?: LeaderboardEntryAvgAggregateInputType
  _sum?: LeaderboardEntrySumAggregateInputType
  _min?: LeaderboardEntryMinAggregateInputType
  _max?: LeaderboardEntryMaxAggregateInputType
}

export type LeaderboardEntryGroupByOutputType = {
  id: string
  contestId: string
  userId: string
  score: number
  rank: number
  updatedAt: Date
  _count: LeaderboardEntryCountAggregateOutputType | null
  _avg: LeaderboardEntryAvgAggregateOutputType | null
  _sum: LeaderboardEntrySumAggregateOutputType | null
  _min: LeaderboardEntryMinAggregateOutputType | null
  _max: LeaderboardEntryMaxAggregateOutputType | null
}

export type GetLeaderboardEntryGroupByPayload<T extends LeaderboardEntryGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<LeaderboardEntryGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof LeaderboardEntryGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], LeaderboardEntryGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], LeaderboardEntryGroupByOutputType[P]>
      }
    >
  >



export type LeaderboardEntryWhereInput = {
  AND?: Prisma.LeaderboardEntryWhereInput | Prisma.LeaderboardEntryWhereInput[]
  OR?: Prisma.LeaderboardEntryWhereInput[]
  NOT?: Prisma.LeaderboardEntryWhereInput | Prisma.LeaderboardEntryWhereInput[]
  id?: Prisma.StringFilter<"LeaderboardEntry"> | string
  contestId?: Prisma.StringFilter<"LeaderboardEntry"> | string
  userId?: Prisma.StringFilter<"LeaderboardEntry"> | string
  score?: Prisma.IntFilter<"LeaderboardEntry"> | number
  rank?: Prisma.IntFilter<"LeaderboardEntry"> | number
  updatedAt?: Prisma.DateTimeFilter<"LeaderboardEntry"> | Date | string
  contest?: Prisma.XOR<Prisma.ContestScalarRelationFilter, Prisma.ContestWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}

export type LeaderboardEntryOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  contest?: Prisma.ContestOrderByWithRelationInput
  user?: Prisma.UserOrderByWithRelationInput
}

export type LeaderboardEntryWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  contestId_userId?: Prisma.LeaderboardEntryContestIdUserIdCompoundUniqueInput
  contestId_rank?: Prisma.LeaderboardEntryContestIdRankCompoundUniqueInput
  AND?: Prisma.LeaderboardEntryWhereInput | Prisma.LeaderboardEntryWhereInput[]
  OR?: Prisma.LeaderboardEntryWhereInput[]
  NOT?: Prisma.LeaderboardEntryWhereInput | Prisma.LeaderboardEntryWhereInput[]
  contestId?: Prisma.StringFilter<"LeaderboardEntry"> | string
  userId?: Prisma.StringFilter<"LeaderboardEntry"> | string
  score?: Prisma.IntFilter<"LeaderboardEntry"> | number
  rank?: Prisma.IntFilter<"LeaderboardEntry"> | number
  updatedAt?: Prisma.DateTimeFilter<"LeaderboardEntry"> | Date | string
  contest?: Prisma.XOR<Prisma.ContestScalarRelationFilter, Prisma.ContestWhereInput>
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
}, "id" | "contestId_userId" | "contestId_rank">

export type LeaderboardEntryOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
  _count?: Prisma.LeaderboardEntryCountOrderByAggregateInput
  _avg?: Prisma.LeaderboardEntryAvgOrderByAggregateInput
  _max?: Prisma.LeaderboardEntryMaxOrderByAggregateInput
  _min?: Prisma.LeaderboardEntryMinOrderByAggregateInput
  _sum?: Prisma.LeaderboardEntrySumOrderByAggregateInput
}

export type LeaderboardEntryScalarWhereWithAggregatesInput = {
  AND?: Prisma.LeaderboardEntryScalarWhereWithAggregatesInput | Prisma.LeaderboardEntryScalarWhereWithAggregatesInput[]
  OR?: Prisma.LeaderboardEntryScalarWhereWithAggregatesInput[]
  NOT?: Prisma.LeaderboardEntryScalarWhereWithAggregatesInput | Prisma.LeaderboardEntryScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"LeaderboardEntry"> | string
  contestId?: Prisma.StringWithAggregatesFilter<"LeaderboardEntry"> | string
  userId?: Prisma.StringWithAggregatesFilter<"LeaderboardEntry"> | string
  score?: Prisma.IntWithAggregatesFilter<"LeaderboardEntry"> | number
  rank?: Prisma.IntWithAggregatesFilter<"LeaderboardEntry"> | number
  updatedAt?: Prisma.DateTimeWithAggregatesFilter<"LeaderboardEntry"> | Date | string
}

export type LeaderboardEntryCreateInput = {
  id?: string
  score: number
  rank: number
  updatedAt?: Date | string
  contest: Prisma.ContestCreateNestedOneWithoutLeaderboardInput
  user: Prisma.UserCreateNestedOneWithoutLeaderboardInput
}

export type LeaderboardEntryUncheckedCreateInput = {
  id?: string
  contestId: string
  userId: string
  score: number
  rank: number
  updatedAt?: Date | string
}

export type LeaderboardEntryUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contest?: Prisma.ContestUpdateOneRequiredWithoutLeaderboardNestedInput
  user?: Prisma.UserUpdateOneRequiredWithoutLeaderboardNestedInput
}

export type LeaderboardEntryUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeaderboardEntryCreateManyInput = {
  id?: string
  contestId: string
  userId: string
  score: number
  rank: number
  updatedAt?: Date | string
}

export type LeaderboardEntryUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeaderboardEntryUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeaderboardEntryListRelationFilter = {
  every?: Prisma.LeaderboardEntryWhereInput
  some?: Prisma.LeaderboardEntryWhereInput
  none?: Prisma.LeaderboardEntryWhereInput
}

export type LeaderboardEntryOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type LeaderboardEntryContestIdUserIdCompoundUniqueInput = {
  contestId: string
  userId: string
}

export type LeaderboardEntryContestIdRankCompoundUniqueInput = {
  contestId: string
  rank: number
}

export type LeaderboardEntryCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeaderboardEntryAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type LeaderboardEntryMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeaderboardEntryMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  score?: Prisma.SortOrder
  rank?: Prisma.SortOrder
  updatedAt?: Prisma.SortOrder
}

export type LeaderboardEntrySumOrderByAggregateInput = {
  score?: Prisma.SortOrder
  rank?: Prisma.SortOrder
}

export type LeaderboardEntryCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutUserInput, Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput> | Prisma.LeaderboardEntryCreateWithoutUserInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput | Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyUserInputEnvelope
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
}

export type LeaderboardEntryUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutUserInput, Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput> | Prisma.LeaderboardEntryCreateWithoutUserInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput | Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyUserInputEnvelope
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
}

export type LeaderboardEntryUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutUserInput, Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput> | Prisma.LeaderboardEntryCreateWithoutUserInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput | Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutUserInput | Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyUserInputEnvelope
  set?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  disconnect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  delete?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  update?: Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutUserInput | Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LeaderboardEntryUpdateManyWithWhereWithoutUserInput | Prisma.LeaderboardEntryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LeaderboardEntryScalarWhereInput | Prisma.LeaderboardEntryScalarWhereInput[]
}

export type LeaderboardEntryUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutUserInput, Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput> | Prisma.LeaderboardEntryCreateWithoutUserInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput | Prisma.LeaderboardEntryCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutUserInput | Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyUserInputEnvelope
  set?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  disconnect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  delete?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  update?: Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutUserInput | Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.LeaderboardEntryUpdateManyWithWhereWithoutUserInput | Prisma.LeaderboardEntryUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.LeaderboardEntryScalarWhereInput | Prisma.LeaderboardEntryScalarWhereInput[]
}

export type LeaderboardEntryCreateNestedManyWithoutContestInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutContestInput, Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput> | Prisma.LeaderboardEntryCreateWithoutContestInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput | Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyContestInputEnvelope
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
}

export type LeaderboardEntryUncheckedCreateNestedManyWithoutContestInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutContestInput, Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput> | Prisma.LeaderboardEntryCreateWithoutContestInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput | Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyContestInputEnvelope
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
}

export type LeaderboardEntryUpdateManyWithoutContestNestedInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutContestInput, Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput> | Prisma.LeaderboardEntryCreateWithoutContestInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput | Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput[]
  upsert?: Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutContestInput | Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutContestInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyContestInputEnvelope
  set?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  disconnect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  delete?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  update?: Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutContestInput | Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutContestInput[]
  updateMany?: Prisma.LeaderboardEntryUpdateManyWithWhereWithoutContestInput | Prisma.LeaderboardEntryUpdateManyWithWhereWithoutContestInput[]
  deleteMany?: Prisma.LeaderboardEntryScalarWhereInput | Prisma.LeaderboardEntryScalarWhereInput[]
}

export type LeaderboardEntryUncheckedUpdateManyWithoutContestNestedInput = {
  create?: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutContestInput, Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput> | Prisma.LeaderboardEntryCreateWithoutContestInput[] | Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput | Prisma.LeaderboardEntryCreateOrConnectWithoutContestInput[]
  upsert?: Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutContestInput | Prisma.LeaderboardEntryUpsertWithWhereUniqueWithoutContestInput[]
  createMany?: Prisma.LeaderboardEntryCreateManyContestInputEnvelope
  set?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  disconnect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  delete?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  connect?: Prisma.LeaderboardEntryWhereUniqueInput | Prisma.LeaderboardEntryWhereUniqueInput[]
  update?: Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutContestInput | Prisma.LeaderboardEntryUpdateWithWhereUniqueWithoutContestInput[]
  updateMany?: Prisma.LeaderboardEntryUpdateManyWithWhereWithoutContestInput | Prisma.LeaderboardEntryUpdateManyWithWhereWithoutContestInput[]
  deleteMany?: Prisma.LeaderboardEntryScalarWhereInput | Prisma.LeaderboardEntryScalarWhereInput[]
}

export type LeaderboardEntryCreateWithoutUserInput = {
  id?: string
  score: number
  rank: number
  updatedAt?: Date | string
  contest: Prisma.ContestCreateNestedOneWithoutLeaderboardInput
}

export type LeaderboardEntryUncheckedCreateWithoutUserInput = {
  id?: string
  contestId: string
  score: number
  rank: number
  updatedAt?: Date | string
}

export type LeaderboardEntryCreateOrConnectWithoutUserInput = {
  where: Prisma.LeaderboardEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutUserInput, Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput>
}

export type LeaderboardEntryCreateManyUserInputEnvelope = {
  data: Prisma.LeaderboardEntryCreateManyUserInput | Prisma.LeaderboardEntryCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type LeaderboardEntryUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.LeaderboardEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.LeaderboardEntryUpdateWithoutUserInput, Prisma.LeaderboardEntryUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutUserInput, Prisma.LeaderboardEntryUncheckedCreateWithoutUserInput>
}

export type LeaderboardEntryUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.LeaderboardEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.LeaderboardEntryUpdateWithoutUserInput, Prisma.LeaderboardEntryUncheckedUpdateWithoutUserInput>
}

export type LeaderboardEntryUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.LeaderboardEntryScalarWhereInput
  data: Prisma.XOR<Prisma.LeaderboardEntryUpdateManyMutationInput, Prisma.LeaderboardEntryUncheckedUpdateManyWithoutUserInput>
}

export type LeaderboardEntryScalarWhereInput = {
  AND?: Prisma.LeaderboardEntryScalarWhereInput | Prisma.LeaderboardEntryScalarWhereInput[]
  OR?: Prisma.LeaderboardEntryScalarWhereInput[]
  NOT?: Prisma.LeaderboardEntryScalarWhereInput | Prisma.LeaderboardEntryScalarWhereInput[]
  id?: Prisma.StringFilter<"LeaderboardEntry"> | string
  contestId?: Prisma.StringFilter<"LeaderboardEntry"> | string
  userId?: Prisma.StringFilter<"LeaderboardEntry"> | string
  score?: Prisma.IntFilter<"LeaderboardEntry"> | number
  rank?: Prisma.IntFilter<"LeaderboardEntry"> | number
  updatedAt?: Prisma.DateTimeFilter<"LeaderboardEntry"> | Date | string
}

export type LeaderboardEntryCreateWithoutContestInput = {
  id?: string
  score: number
  rank: number
  updatedAt?: Date | string
  user: Prisma.UserCreateNestedOneWithoutLeaderboardInput
}

export type LeaderboardEntryUncheckedCreateWithoutContestInput = {
  id?: string
  userId: string
  score: number
  rank: number
  updatedAt?: Date | string
}

export type LeaderboardEntryCreateOrConnectWithoutContestInput = {
  where: Prisma.LeaderboardEntryWhereUniqueInput
  create: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutContestInput, Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput>
}

export type LeaderboardEntryCreateManyContestInputEnvelope = {
  data: Prisma.LeaderboardEntryCreateManyContestInput | Prisma.LeaderboardEntryCreateManyContestInput[]
  skipDuplicates?: boolean
}

export type LeaderboardEntryUpsertWithWhereUniqueWithoutContestInput = {
  where: Prisma.LeaderboardEntryWhereUniqueInput
  update: Prisma.XOR<Prisma.LeaderboardEntryUpdateWithoutContestInput, Prisma.LeaderboardEntryUncheckedUpdateWithoutContestInput>
  create: Prisma.XOR<Prisma.LeaderboardEntryCreateWithoutContestInput, Prisma.LeaderboardEntryUncheckedCreateWithoutContestInput>
}

export type LeaderboardEntryUpdateWithWhereUniqueWithoutContestInput = {
  where: Prisma.LeaderboardEntryWhereUniqueInput
  data: Prisma.XOR<Prisma.LeaderboardEntryUpdateWithoutContestInput, Prisma.LeaderboardEntryUncheckedUpdateWithoutContestInput>
}

export type LeaderboardEntryUpdateManyWithWhereWithoutContestInput = {
  where: Prisma.LeaderboardEntryScalarWhereInput
  data: Prisma.XOR<Prisma.LeaderboardEntryUpdateManyMutationInput, Prisma.LeaderboardEntryUncheckedUpdateManyWithoutContestInput>
}

export type LeaderboardEntryCreateManyUserInput = {
  id?: string
  contestId: string
  score: number
  rank: number
  updatedAt?: Date | string
}

export type LeaderboardEntryUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  contest?: Prisma.ContestUpdateOneRequiredWithoutLeaderboardNestedInput
}

export type LeaderboardEntryUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeaderboardEntryUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeaderboardEntryCreateManyContestInput = {
  id?: string
  userId: string
  score: number
  rank: number
  updatedAt?: Date | string
}

export type LeaderboardEntryUpdateWithoutContestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  user?: Prisma.UserUpdateOneRequiredWithoutLeaderboardNestedInput
}

export type LeaderboardEntryUncheckedUpdateWithoutContestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}

export type LeaderboardEntryUncheckedUpdateManyWithoutContestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  score?: Prisma.IntFieldUpdateOperationsInput | number
  rank?: Prisma.IntFieldUpdateOperationsInput | number
  updatedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
}



export type LeaderboardEntrySelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  contestId?: boolean
  userId?: boolean
  score?: boolean
  rank?: boolean
  updatedAt?: boolean
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leaderboardEntry"]>

export type LeaderboardEntrySelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  contestId?: boolean
  userId?: boolean
  score?: boolean
  rank?: boolean
  updatedAt?: boolean
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leaderboardEntry"]>

export type LeaderboardEntrySelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  contestId?: boolean
  userId?: boolean
  score?: boolean
  rank?: boolean
  updatedAt?: boolean
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}, ExtArgs["result"]["leaderboardEntry"]>

export type LeaderboardEntrySelectScalar = {
  id?: boolean
  contestId?: boolean
  userId?: boolean
  score?: boolean
  rank?: boolean
  updatedAt?: boolean
}

export type LeaderboardEntryOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "contestId" | "userId" | "score" | "rank" | "updatedAt", ExtArgs["result"]["leaderboardEntry"]>
export type LeaderboardEntryInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LeaderboardEntryIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}
export type LeaderboardEntryIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
}

export type $LeaderboardEntryPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "LeaderboardEntry"
  objects: {
    contest: Prisma.$ContestPayload<ExtArgs>
    user: Prisma.$UserPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    contestId: string
    userId: string
    score: number
    rank: number
    updatedAt: Date
  }, ExtArgs["result"]["leaderboardEntry"]>
  composites: {}
}

export type LeaderboardEntryGetPayload<S extends boolean | null | undefined | LeaderboardEntryDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload, S>

export type LeaderboardEntryCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<LeaderboardEntryFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: LeaderboardEntryCountAggregateInputType | true
  }

export interface LeaderboardEntryDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['LeaderboardEntry'], meta: { name: 'LeaderboardEntry' } }
  /**
   * Find zero or one LeaderboardEntry that matches the filter.
   * @param {LeaderboardEntryFindUniqueArgs} args - Arguments to find a LeaderboardEntry
   * @example
   * // Get one LeaderboardEntry
   * const leaderboardEntry = await prisma.leaderboardEntry.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends LeaderboardEntryFindUniqueArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryFindUniqueArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one LeaderboardEntry that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {LeaderboardEntryFindUniqueOrThrowArgs} args - Arguments to find a LeaderboardEntry
   * @example
   * // Get one LeaderboardEntry
   * const leaderboardEntry = await prisma.leaderboardEntry.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends LeaderboardEntryFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LeaderboardEntry that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaderboardEntryFindFirstArgs} args - Arguments to find a LeaderboardEntry
   * @example
   * // Get one LeaderboardEntry
   * const leaderboardEntry = await prisma.leaderboardEntry.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends LeaderboardEntryFindFirstArgs>(args?: Prisma.SelectSubset<T, LeaderboardEntryFindFirstArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first LeaderboardEntry that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaderboardEntryFindFirstOrThrowArgs} args - Arguments to find a LeaderboardEntry
   * @example
   * // Get one LeaderboardEntry
   * const leaderboardEntry = await prisma.leaderboardEntry.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends LeaderboardEntryFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, LeaderboardEntryFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more LeaderboardEntries that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaderboardEntryFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all LeaderboardEntries
   * const leaderboardEntries = await prisma.leaderboardEntry.findMany()
   * 
   * // Get first 10 LeaderboardEntries
   * const leaderboardEntries = await prisma.leaderboardEntry.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const leaderboardEntryWithIdOnly = await prisma.leaderboardEntry.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends LeaderboardEntryFindManyArgs>(args?: Prisma.SelectSubset<T, LeaderboardEntryFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a LeaderboardEntry.
   * @param {LeaderboardEntryCreateArgs} args - Arguments to create a LeaderboardEntry.
   * @example
   * // Create one LeaderboardEntry
   * const LeaderboardEntry = await prisma.leaderboardEntry.create({
   *   data: {
   *     // ... data to create a LeaderboardEntry
   *   }
   * })
   * 
   */
  create<T extends LeaderboardEntryCreateArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryCreateArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many LeaderboardEntries.
   * @param {LeaderboardEntryCreateManyArgs} args - Arguments to create many LeaderboardEntries.
   * @example
   * // Create many LeaderboardEntries
   * const leaderboardEntry = await prisma.leaderboardEntry.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends LeaderboardEntryCreateManyArgs>(args?: Prisma.SelectSubset<T, LeaderboardEntryCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many LeaderboardEntries and returns the data saved in the database.
   * @param {LeaderboardEntryCreateManyAndReturnArgs} args - Arguments to create many LeaderboardEntries.
   * @example
   * // Create many LeaderboardEntries
   * const leaderboardEntry = await prisma.leaderboardEntry.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many LeaderboardEntries and only return the `id`
   * const leaderboardEntryWithIdOnly = await prisma.leaderboardEntry.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends LeaderboardEntryCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, LeaderboardEntryCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a LeaderboardEntry.
   * @param {LeaderboardEntryDeleteArgs} args - Arguments to delete one LeaderboardEntry.
   * @example
   * // Delete one LeaderboardEntry
   * const LeaderboardEntry = await prisma.leaderboardEntry.delete({
   *   where: {
   *     // ... filter to delete one LeaderboardEntry
   *   }
   * })
   * 
   */
  delete<T extends LeaderboardEntryDeleteArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryDeleteArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one LeaderboardEntry.
   * @param {LeaderboardEntryUpdateArgs} args - Arguments to update one LeaderboardEntry.
   * @example
   * // Update one LeaderboardEntry
   * const leaderboardEntry = await prisma.leaderboardEntry.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends LeaderboardEntryUpdateArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryUpdateArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more LeaderboardEntries.
   * @param {LeaderboardEntryDeleteManyArgs} args - Arguments to filter LeaderboardEntries to delete.
   * @example
   * // Delete a few LeaderboardEntries
   * const { count } = await prisma.leaderboardEntry.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends LeaderboardEntryDeleteManyArgs>(args?: Prisma.SelectSubset<T, LeaderboardEntryDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LeaderboardEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaderboardEntryUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many LeaderboardEntries
   * const leaderboardEntry = await prisma.leaderboardEntry.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends LeaderboardEntryUpdateManyArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more LeaderboardEntries and returns the data updated in the database.
   * @param {LeaderboardEntryUpdateManyAndReturnArgs} args - Arguments to update many LeaderboardEntries.
   * @example
   * // Update many LeaderboardEntries
   * const leaderboardEntry = await prisma.leaderboardEntry.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more LeaderboardEntries and only return the `id`
   * const leaderboardEntryWithIdOnly = await prisma.leaderboardEntry.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends LeaderboardEntryUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one LeaderboardEntry.
   * @param {LeaderboardEntryUpsertArgs} args - Arguments to update or create a LeaderboardEntry.
   * @example
   * // Update or create a LeaderboardEntry
   * const leaderboardEntry = await prisma.leaderboardEntry.upsert({
   *   create: {
   *     // ... data to create a LeaderboardEntry
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the LeaderboardEntry we want to update
   *   }
   * })
   */
  upsert<T extends LeaderboardEntryUpsertArgs>(args: Prisma.SelectSubset<T, LeaderboardEntryUpsertArgs<ExtArgs>>): Prisma.Prisma__LeaderboardEntryClient<runtime.Types.Result.GetResult<Prisma.$LeaderboardEntryPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of LeaderboardEntries.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaderboardEntryCountArgs} args - Arguments to filter LeaderboardEntries to count.
   * @example
   * // Count the number of LeaderboardEntries
   * const count = await prisma.leaderboardEntry.count({
   *   where: {
   *     // ... the filter for the LeaderboardEntries we want to count
   *   }
   * })
  **/
  count<T extends LeaderboardEntryCountArgs>(
    args?: Prisma.Subset<T, LeaderboardEntryCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], LeaderboardEntryCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a LeaderboardEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaderboardEntryAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends LeaderboardEntryAggregateArgs>(args: Prisma.Subset<T, LeaderboardEntryAggregateArgs>): Prisma.PrismaPromise<GetLeaderboardEntryAggregateType<T>>

  /**
   * Group by LeaderboardEntry.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {LeaderboardEntryGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends LeaderboardEntryGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: LeaderboardEntryGroupByArgs['orderBy'] }
      : { orderBy?: LeaderboardEntryGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, LeaderboardEntryGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetLeaderboardEntryGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the LeaderboardEntry model
 */
readonly fields: LeaderboardEntryFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for LeaderboardEntry.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__LeaderboardEntryClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  contest<T extends Prisma.ContestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ContestDefaultArgs<ExtArgs>>): Prisma.Prisma__ContestClient<runtime.Types.Result.GetResult<Prisma.$ContestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the LeaderboardEntry model
 */
export interface LeaderboardEntryFieldRefs {
  readonly id: Prisma.FieldRef<"LeaderboardEntry", 'String'>
  readonly contestId: Prisma.FieldRef<"LeaderboardEntry", 'String'>
  readonly userId: Prisma.FieldRef<"LeaderboardEntry", 'String'>
  readonly score: Prisma.FieldRef<"LeaderboardEntry", 'Int'>
  readonly rank: Prisma.FieldRef<"LeaderboardEntry", 'Int'>
  readonly updatedAt: Prisma.FieldRef<"LeaderboardEntry", 'DateTime'>
}
    

// Custom InputTypes
/**
 * LeaderboardEntry findUnique
 */
export type LeaderboardEntryFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * Filter, which LeaderboardEntry to fetch.
   */
  where: Prisma.LeaderboardEntryWhereUniqueInput
}

/**
 * LeaderboardEntry findUniqueOrThrow
 */
export type LeaderboardEntryFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * Filter, which LeaderboardEntry to fetch.
   */
  where: Prisma.LeaderboardEntryWhereUniqueInput
}

/**
 * LeaderboardEntry findFirst
 */
export type LeaderboardEntryFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * Filter, which LeaderboardEntry to fetch.
   */
  where?: Prisma.LeaderboardEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaderboardEntries to fetch.
   */
  orderBy?: Prisma.LeaderboardEntryOrderByWithRelationInput | Prisma.LeaderboardEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LeaderboardEntries.
   */
  cursor?: Prisma.LeaderboardEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaderboardEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaderboardEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LeaderboardEntries.
   */
  distinct?: Prisma.LeaderboardEntryScalarFieldEnum | Prisma.LeaderboardEntryScalarFieldEnum[]
}

/**
 * LeaderboardEntry findFirstOrThrow
 */
export type LeaderboardEntryFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * Filter, which LeaderboardEntry to fetch.
   */
  where?: Prisma.LeaderboardEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaderboardEntries to fetch.
   */
  orderBy?: Prisma.LeaderboardEntryOrderByWithRelationInput | Prisma.LeaderboardEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for LeaderboardEntries.
   */
  cursor?: Prisma.LeaderboardEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaderboardEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaderboardEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LeaderboardEntries.
   */
  distinct?: Prisma.LeaderboardEntryScalarFieldEnum | Prisma.LeaderboardEntryScalarFieldEnum[]
}

/**
 * LeaderboardEntry findMany
 */
export type LeaderboardEntryFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * Filter, which LeaderboardEntries to fetch.
   */
  where?: Prisma.LeaderboardEntryWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of LeaderboardEntries to fetch.
   */
  orderBy?: Prisma.LeaderboardEntryOrderByWithRelationInput | Prisma.LeaderboardEntryOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing LeaderboardEntries.
   */
  cursor?: Prisma.LeaderboardEntryWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` LeaderboardEntries from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` LeaderboardEntries.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of LeaderboardEntries.
   */
  distinct?: Prisma.LeaderboardEntryScalarFieldEnum | Prisma.LeaderboardEntryScalarFieldEnum[]
}

/**
 * LeaderboardEntry create
 */
export type LeaderboardEntryCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * The data needed to create a LeaderboardEntry.
   */
  data: Prisma.XOR<Prisma.LeaderboardEntryCreateInput, Prisma.LeaderboardEntryUncheckedCreateInput>
}

/**
 * LeaderboardEntry createMany
 */
export type LeaderboardEntryCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many LeaderboardEntries.
   */
  data: Prisma.LeaderboardEntryCreateManyInput | Prisma.LeaderboardEntryCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * LeaderboardEntry createManyAndReturn
 */
export type LeaderboardEntryCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * The data used to create many LeaderboardEntries.
   */
  data: Prisma.LeaderboardEntryCreateManyInput | Prisma.LeaderboardEntryCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * LeaderboardEntry update
 */
export type LeaderboardEntryUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * The data needed to update a LeaderboardEntry.
   */
  data: Prisma.XOR<Prisma.LeaderboardEntryUpdateInput, Prisma.LeaderboardEntryUncheckedUpdateInput>
  /**
   * Choose, which LeaderboardEntry to update.
   */
  where: Prisma.LeaderboardEntryWhereUniqueInput
}

/**
 * LeaderboardEntry updateMany
 */
export type LeaderboardEntryUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update LeaderboardEntries.
   */
  data: Prisma.XOR<Prisma.LeaderboardEntryUpdateManyMutationInput, Prisma.LeaderboardEntryUncheckedUpdateManyInput>
  /**
   * Filter which LeaderboardEntries to update
   */
  where?: Prisma.LeaderboardEntryWhereInput
  /**
   * Limit how many LeaderboardEntries to update.
   */
  limit?: number
}

/**
 * LeaderboardEntry updateManyAndReturn
 */
export type LeaderboardEntryUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * The data used to update LeaderboardEntries.
   */
  data: Prisma.XOR<Prisma.LeaderboardEntryUpdateManyMutationInput, Prisma.LeaderboardEntryUncheckedUpdateManyInput>
  /**
   * Filter which LeaderboardEntries to update
   */
  where?: Prisma.LeaderboardEntryWhereInput
  /**
   * Limit how many LeaderboardEntries to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * LeaderboardEntry upsert
 */
export type LeaderboardEntryUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * The filter to search for the LeaderboardEntry to update in case it exists.
   */
  where: Prisma.LeaderboardEntryWhereUniqueInput
  /**
   * In case the LeaderboardEntry found by the `where` argument doesn't exist, create a new LeaderboardEntry with this data.
   */
  create: Prisma.XOR<Prisma.LeaderboardEntryCreateInput, Prisma.LeaderboardEntryUncheckedCreateInput>
  /**
   * In case the LeaderboardEntry was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.LeaderboardEntryUpdateInput, Prisma.LeaderboardEntryUncheckedUpdateInput>
}

/**
 * LeaderboardEntry delete
 */
export type LeaderboardEntryDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
  /**
   * Filter which LeaderboardEntry to delete.
   */
  where: Prisma.LeaderboardEntryWhereUniqueInput
}

/**
 * LeaderboardEntry deleteMany
 */
export type LeaderboardEntryDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which LeaderboardEntries to delete
   */
  where?: Prisma.LeaderboardEntryWhereInput
  /**
   * Limit how many LeaderboardEntries to delete.
   */
  limit?: number
}

/**
 * LeaderboardEntry without action
 */
export type LeaderboardEntryDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the LeaderboardEntry
   */
  select?: Prisma.LeaderboardEntrySelect<ExtArgs> | null
  /**
   * Omit specific fields from the LeaderboardEntry
   */
  omit?: Prisma.LeaderboardEntryOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.LeaderboardEntryInclude<ExtArgs> | null
}
