
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `Participation` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model Participation
 * 
 */
export type ParticipationModel = runtime.Types.Result.DefaultSelection<Prisma.$ParticipationPayload>

export type AggregateParticipation = {
  _count: ParticipationCountAggregateOutputType | null
  _avg: ParticipationAvgAggregateOutputType | null
  _sum: ParticipationSumAggregateOutputType | null
  _min: ParticipationMinAggregateOutputType | null
  _max: ParticipationMaxAggregateOutputType | null
}

export type ParticipationAvgAggregateOutputType = {
  score: number | null
}

export type ParticipationSumAggregateOutputType = {
  score: number | null
}

export type ParticipationMinAggregateOutputType = {
  id: string | null
  userId: string | null
  contestId: string | null
  status: $Enums.ParticipationStatus | null
  score: number | null
  startedAt: Date | null
  submittedAt: Date | null
}

export type ParticipationMaxAggregateOutputType = {
  id: string | null
  userId: string | null
  contestId: string | null
  status: $Enums.ParticipationStatus | null
  score: number | null
  startedAt: Date | null
  submittedAt: Date | null
}

export type ParticipationCountAggregateOutputType = {
  id: number
  userId: number
  contestId: number
  status: number
  score: number
  startedAt: number
  submittedAt: number
  _all: number
}


export type ParticipationAvgAggregateInputType = {
  score?: true
}

export type ParticipationSumAggregateInputType = {
  score?: true
}

export type ParticipationMinAggregateInputType = {
  id?: true
  userId?: true
  contestId?: true
  status?: true
  score?: true
  startedAt?: true
  submittedAt?: true
}

export type ParticipationMaxAggregateInputType = {
  id?: true
  userId?: true
  contestId?: true
  status?: true
  score?: true
  startedAt?: true
  submittedAt?: true
}

export type ParticipationCountAggregateInputType = {
  id?: true
  userId?: true
  contestId?: true
  status?: true
  score?: true
  startedAt?: true
  submittedAt?: true
  _all?: true
}

export type ParticipationAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Participation to aggregate.
   */
  where?: Prisma.ParticipationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participations to fetch.
   */
  orderBy?: Prisma.ParticipationOrderByWithRelationInput | Prisma.ParticipationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.ParticipationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned Participations
  **/
  _count?: true | ParticipationCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: ParticipationAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: ParticipationSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: ParticipationMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: ParticipationMaxAggregateInputType
}

export type GetParticipationAggregateType<T extends ParticipationAggregateArgs> = {
      [P in keyof T & keyof AggregateParticipation]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregateParticipation[P]>
    : Prisma.GetScalarType<T[P], AggregateParticipation[P]>
}




export type ParticipationGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.ParticipationWhereInput
  orderBy?: Prisma.ParticipationOrderByWithAggregationInput | Prisma.ParticipationOrderByWithAggregationInput[]
  by: Prisma.ParticipationScalarFieldEnum[] | Prisma.ParticipationScalarFieldEnum
  having?: Prisma.ParticipationScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: ParticipationCountAggregateInputType | true
  _avg?: ParticipationAvgAggregateInputType
  _sum?: ParticipationSumAggregateInputType
  _min?: ParticipationMinAggregateInputType
  _max?: ParticipationMaxAggregateInputType
}

export type ParticipationGroupByOutputType = {
  id: string
  userId: string
  contestId: string
  status: $Enums.ParticipationStatus
  score: number
  startedAt: Date
  submittedAt: Date | null
  _count: ParticipationCountAggregateOutputType | null
  _avg: ParticipationAvgAggregateOutputType | null
  _sum: ParticipationSumAggregateOutputType | null
  _min: ParticipationMinAggregateOutputType | null
  _max: ParticipationMaxAggregateOutputType | null
}

export type GetParticipationGroupByPayload<T extends ParticipationGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<ParticipationGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof ParticipationGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], ParticipationGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], ParticipationGroupByOutputType[P]>
      }
    >
  >



export type ParticipationWhereInput = {
  AND?: Prisma.ParticipationWhereInput | Prisma.ParticipationWhereInput[]
  OR?: Prisma.ParticipationWhereInput[]
  NOT?: Prisma.ParticipationWhereInput | Prisma.ParticipationWhereInput[]
  id?: Prisma.StringFilter<"Participation"> | string
  userId?: Prisma.StringFilter<"Participation"> | string
  contestId?: Prisma.StringFilter<"Participation"> | string
  status?: Prisma.EnumParticipationStatusFilter<"Participation"> | $Enums.ParticipationStatus
  score?: Prisma.IntFilter<"Participation"> | number
  startedAt?: Prisma.DateTimeFilter<"Participation"> | Date | string
  submittedAt?: Prisma.DateTimeNullableFilter<"Participation"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  contest?: Prisma.XOR<Prisma.ContestScalarRelationFilter, Prisma.ContestWhereInput>
  answers?: Prisma.AnswerListRelationFilter
}

export type ParticipationOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  score?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  user?: Prisma.UserOrderByWithRelationInput
  contest?: Prisma.ContestOrderByWithRelationInput
  answers?: Prisma.AnswerOrderByRelationAggregateInput
}

export type ParticipationWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  userId_contestId?: Prisma.ParticipationUserIdContestIdCompoundUniqueInput
  AND?: Prisma.ParticipationWhereInput | Prisma.ParticipationWhereInput[]
  OR?: Prisma.ParticipationWhereInput[]
  NOT?: Prisma.ParticipationWhereInput | Prisma.ParticipationWhereInput[]
  userId?: Prisma.StringFilter<"Participation"> | string
  contestId?: Prisma.StringFilter<"Participation"> | string
  status?: Prisma.EnumParticipationStatusFilter<"Participation"> | $Enums.ParticipationStatus
  score?: Prisma.IntFilter<"Participation"> | number
  startedAt?: Prisma.DateTimeFilter<"Participation"> | Date | string
  submittedAt?: Prisma.DateTimeNullableFilter<"Participation"> | Date | string | null
  user?: Prisma.XOR<Prisma.UserScalarRelationFilter, Prisma.UserWhereInput>
  contest?: Prisma.XOR<Prisma.ContestScalarRelationFilter, Prisma.ContestWhereInput>
  answers?: Prisma.AnswerListRelationFilter
}, "id" | "userId_contestId">

export type ParticipationOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  score?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.ParticipationCountOrderByAggregateInput
  _avg?: Prisma.ParticipationAvgOrderByAggregateInput
  _max?: Prisma.ParticipationMaxOrderByAggregateInput
  _min?: Prisma.ParticipationMinOrderByAggregateInput
  _sum?: Prisma.ParticipationSumOrderByAggregateInput
}

export type ParticipationScalarWhereWithAggregatesInput = {
  AND?: Prisma.ParticipationScalarWhereWithAggregatesInput | Prisma.ParticipationScalarWhereWithAggregatesInput[]
  OR?: Prisma.ParticipationScalarWhereWithAggregatesInput[]
  NOT?: Prisma.ParticipationScalarWhereWithAggregatesInput | Prisma.ParticipationScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"Participation"> | string
  userId?: Prisma.StringWithAggregatesFilter<"Participation"> | string
  contestId?: Prisma.StringWithAggregatesFilter<"Participation"> | string
  status?: Prisma.EnumParticipationStatusWithAggregatesFilter<"Participation"> | $Enums.ParticipationStatus
  score?: Prisma.IntWithAggregatesFilter<"Participation"> | number
  startedAt?: Prisma.DateTimeWithAggregatesFilter<"Participation"> | Date | string
  submittedAt?: Prisma.DateTimeNullableWithAggregatesFilter<"Participation"> | Date | string | null
}

export type ParticipationCreateInput = {
  id?: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutParticipationsInput
  contest: Prisma.ContestCreateNestedOneWithoutParticipationsInput
  answers?: Prisma.AnswerCreateNestedManyWithoutParticipationInput
}

export type ParticipationUncheckedCreateInput = {
  id?: string
  userId: string
  contestId: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutParticipationInput
}

export type ParticipationUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutParticipationsNestedInput
  contest?: Prisma.ContestUpdateOneRequiredWithoutParticipationsNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutParticipationNestedInput
}

export type ParticipationUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutParticipationNestedInput
}

export type ParticipationCreateManyInput = {
  id?: string
  userId: string
  contestId: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
}

export type ParticipationUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ParticipationUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ParticipationListRelationFilter = {
  every?: Prisma.ParticipationWhereInput
  some?: Prisma.ParticipationWhereInput
  none?: Prisma.ParticipationWhereInput
}

export type ParticipationOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type ParticipationUserIdContestIdCompoundUniqueInput = {
  userId: string
  contestId: string
}

export type ParticipationCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  score?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
}

export type ParticipationAvgOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type ParticipationMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  score?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
}

export type ParticipationMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  userId?: Prisma.SortOrder
  contestId?: Prisma.SortOrder
  status?: Prisma.SortOrder
  score?: Prisma.SortOrder
  startedAt?: Prisma.SortOrder
  submittedAt?: Prisma.SortOrder
}

export type ParticipationSumOrderByAggregateInput = {
  score?: Prisma.SortOrder
}

export type ParticipationScalarRelationFilter = {
  is?: Prisma.ParticipationWhereInput
  isNot?: Prisma.ParticipationWhereInput
}

export type ParticipationCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutUserInput, Prisma.ParticipationUncheckedCreateWithoutUserInput> | Prisma.ParticipationCreateWithoutUserInput[] | Prisma.ParticipationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutUserInput | Prisma.ParticipationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ParticipationCreateManyUserInputEnvelope
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
}

export type ParticipationUncheckedCreateNestedManyWithoutUserInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutUserInput, Prisma.ParticipationUncheckedCreateWithoutUserInput> | Prisma.ParticipationCreateWithoutUserInput[] | Prisma.ParticipationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutUserInput | Prisma.ParticipationCreateOrConnectWithoutUserInput[]
  createMany?: Prisma.ParticipationCreateManyUserInputEnvelope
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
}

export type ParticipationUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutUserInput, Prisma.ParticipationUncheckedCreateWithoutUserInput> | Prisma.ParticipationCreateWithoutUserInput[] | Prisma.ParticipationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutUserInput | Prisma.ParticipationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ParticipationUpsertWithWhereUniqueWithoutUserInput | Prisma.ParticipationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ParticipationCreateManyUserInputEnvelope
  set?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  disconnect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  delete?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  update?: Prisma.ParticipationUpdateWithWhereUniqueWithoutUserInput | Prisma.ParticipationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ParticipationUpdateManyWithWhereWithoutUserInput | Prisma.ParticipationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ParticipationScalarWhereInput | Prisma.ParticipationScalarWhereInput[]
}

export type ParticipationUncheckedUpdateManyWithoutUserNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutUserInput, Prisma.ParticipationUncheckedCreateWithoutUserInput> | Prisma.ParticipationCreateWithoutUserInput[] | Prisma.ParticipationUncheckedCreateWithoutUserInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutUserInput | Prisma.ParticipationCreateOrConnectWithoutUserInput[]
  upsert?: Prisma.ParticipationUpsertWithWhereUniqueWithoutUserInput | Prisma.ParticipationUpsertWithWhereUniqueWithoutUserInput[]
  createMany?: Prisma.ParticipationCreateManyUserInputEnvelope
  set?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  disconnect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  delete?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  update?: Prisma.ParticipationUpdateWithWhereUniqueWithoutUserInput | Prisma.ParticipationUpdateWithWhereUniqueWithoutUserInput[]
  updateMany?: Prisma.ParticipationUpdateManyWithWhereWithoutUserInput | Prisma.ParticipationUpdateManyWithWhereWithoutUserInput[]
  deleteMany?: Prisma.ParticipationScalarWhereInput | Prisma.ParticipationScalarWhereInput[]
}

export type ParticipationCreateNestedManyWithoutContestInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutContestInput, Prisma.ParticipationUncheckedCreateWithoutContestInput> | Prisma.ParticipationCreateWithoutContestInput[] | Prisma.ParticipationUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutContestInput | Prisma.ParticipationCreateOrConnectWithoutContestInput[]
  createMany?: Prisma.ParticipationCreateManyContestInputEnvelope
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
}

export type ParticipationUncheckedCreateNestedManyWithoutContestInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutContestInput, Prisma.ParticipationUncheckedCreateWithoutContestInput> | Prisma.ParticipationCreateWithoutContestInput[] | Prisma.ParticipationUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutContestInput | Prisma.ParticipationCreateOrConnectWithoutContestInput[]
  createMany?: Prisma.ParticipationCreateManyContestInputEnvelope
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
}

export type ParticipationUpdateManyWithoutContestNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutContestInput, Prisma.ParticipationUncheckedCreateWithoutContestInput> | Prisma.ParticipationCreateWithoutContestInput[] | Prisma.ParticipationUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutContestInput | Prisma.ParticipationCreateOrConnectWithoutContestInput[]
  upsert?: Prisma.ParticipationUpsertWithWhereUniqueWithoutContestInput | Prisma.ParticipationUpsertWithWhereUniqueWithoutContestInput[]
  createMany?: Prisma.ParticipationCreateManyContestInputEnvelope
  set?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  disconnect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  delete?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  update?: Prisma.ParticipationUpdateWithWhereUniqueWithoutContestInput | Prisma.ParticipationUpdateWithWhereUniqueWithoutContestInput[]
  updateMany?: Prisma.ParticipationUpdateManyWithWhereWithoutContestInput | Prisma.ParticipationUpdateManyWithWhereWithoutContestInput[]
  deleteMany?: Prisma.ParticipationScalarWhereInput | Prisma.ParticipationScalarWhereInput[]
}

export type ParticipationUncheckedUpdateManyWithoutContestNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutContestInput, Prisma.ParticipationUncheckedCreateWithoutContestInput> | Prisma.ParticipationCreateWithoutContestInput[] | Prisma.ParticipationUncheckedCreateWithoutContestInput[]
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutContestInput | Prisma.ParticipationCreateOrConnectWithoutContestInput[]
  upsert?: Prisma.ParticipationUpsertWithWhereUniqueWithoutContestInput | Prisma.ParticipationUpsertWithWhereUniqueWithoutContestInput[]
  createMany?: Prisma.ParticipationCreateManyContestInputEnvelope
  set?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  disconnect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  delete?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  connect?: Prisma.ParticipationWhereUniqueInput | Prisma.ParticipationWhereUniqueInput[]
  update?: Prisma.ParticipationUpdateWithWhereUniqueWithoutContestInput | Prisma.ParticipationUpdateWithWhereUniqueWithoutContestInput[]
  updateMany?: Prisma.ParticipationUpdateManyWithWhereWithoutContestInput | Prisma.ParticipationUpdateManyWithWhereWithoutContestInput[]
  deleteMany?: Prisma.ParticipationScalarWhereInput | Prisma.ParticipationScalarWhereInput[]
}

export type EnumParticipationStatusFieldUpdateOperationsInput = {
  set?: $Enums.ParticipationStatus
}

export type NullableDateTimeFieldUpdateOperationsInput = {
  set?: Date | string | null
}

export type ParticipationCreateNestedOneWithoutAnswersInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutAnswersInput, Prisma.ParticipationUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutAnswersInput
  connect?: Prisma.ParticipationWhereUniqueInput
}

export type ParticipationUpdateOneRequiredWithoutAnswersNestedInput = {
  create?: Prisma.XOR<Prisma.ParticipationCreateWithoutAnswersInput, Prisma.ParticipationUncheckedCreateWithoutAnswersInput>
  connectOrCreate?: Prisma.ParticipationCreateOrConnectWithoutAnswersInput
  upsert?: Prisma.ParticipationUpsertWithoutAnswersInput
  connect?: Prisma.ParticipationWhereUniqueInput
  update?: Prisma.XOR<Prisma.XOR<Prisma.ParticipationUpdateToOneWithWhereWithoutAnswersInput, Prisma.ParticipationUpdateWithoutAnswersInput>, Prisma.ParticipationUncheckedUpdateWithoutAnswersInput>
}

export type ParticipationCreateWithoutUserInput = {
  id?: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
  contest: Prisma.ContestCreateNestedOneWithoutParticipationsInput
  answers?: Prisma.AnswerCreateNestedManyWithoutParticipationInput
}

export type ParticipationUncheckedCreateWithoutUserInput = {
  id?: string
  contestId: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutParticipationInput
}

export type ParticipationCreateOrConnectWithoutUserInput = {
  where: Prisma.ParticipationWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipationCreateWithoutUserInput, Prisma.ParticipationUncheckedCreateWithoutUserInput>
}

export type ParticipationCreateManyUserInputEnvelope = {
  data: Prisma.ParticipationCreateManyUserInput | Prisma.ParticipationCreateManyUserInput[]
  skipDuplicates?: boolean
}

export type ParticipationUpsertWithWhereUniqueWithoutUserInput = {
  where: Prisma.ParticipationWhereUniqueInput
  update: Prisma.XOR<Prisma.ParticipationUpdateWithoutUserInput, Prisma.ParticipationUncheckedUpdateWithoutUserInput>
  create: Prisma.XOR<Prisma.ParticipationCreateWithoutUserInput, Prisma.ParticipationUncheckedCreateWithoutUserInput>
}

export type ParticipationUpdateWithWhereUniqueWithoutUserInput = {
  where: Prisma.ParticipationWhereUniqueInput
  data: Prisma.XOR<Prisma.ParticipationUpdateWithoutUserInput, Prisma.ParticipationUncheckedUpdateWithoutUserInput>
}

export type ParticipationUpdateManyWithWhereWithoutUserInput = {
  where: Prisma.ParticipationScalarWhereInput
  data: Prisma.XOR<Prisma.ParticipationUpdateManyMutationInput, Prisma.ParticipationUncheckedUpdateManyWithoutUserInput>
}

export type ParticipationScalarWhereInput = {
  AND?: Prisma.ParticipationScalarWhereInput | Prisma.ParticipationScalarWhereInput[]
  OR?: Prisma.ParticipationScalarWhereInput[]
  NOT?: Prisma.ParticipationScalarWhereInput | Prisma.ParticipationScalarWhereInput[]
  id?: Prisma.StringFilter<"Participation"> | string
  userId?: Prisma.StringFilter<"Participation"> | string
  contestId?: Prisma.StringFilter<"Participation"> | string
  status?: Prisma.EnumParticipationStatusFilter<"Participation"> | $Enums.ParticipationStatus
  score?: Prisma.IntFilter<"Participation"> | number
  startedAt?: Prisma.DateTimeFilter<"Participation"> | Date | string
  submittedAt?: Prisma.DateTimeNullableFilter<"Participation"> | Date | string | null
}

export type ParticipationCreateWithoutContestInput = {
  id?: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutParticipationsInput
  answers?: Prisma.AnswerCreateNestedManyWithoutParticipationInput
}

export type ParticipationUncheckedCreateWithoutContestInput = {
  id?: string
  userId: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
  answers?: Prisma.AnswerUncheckedCreateNestedManyWithoutParticipationInput
}

export type ParticipationCreateOrConnectWithoutContestInput = {
  where: Prisma.ParticipationWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipationCreateWithoutContestInput, Prisma.ParticipationUncheckedCreateWithoutContestInput>
}

export type ParticipationCreateManyContestInputEnvelope = {
  data: Prisma.ParticipationCreateManyContestInput | Prisma.ParticipationCreateManyContestInput[]
  skipDuplicates?: boolean
}

export type ParticipationUpsertWithWhereUniqueWithoutContestInput = {
  where: Prisma.ParticipationWhereUniqueInput
  update: Prisma.XOR<Prisma.ParticipationUpdateWithoutContestInput, Prisma.ParticipationUncheckedUpdateWithoutContestInput>
  create: Prisma.XOR<Prisma.ParticipationCreateWithoutContestInput, Prisma.ParticipationUncheckedCreateWithoutContestInput>
}

export type ParticipationUpdateWithWhereUniqueWithoutContestInput = {
  where: Prisma.ParticipationWhereUniqueInput
  data: Prisma.XOR<Prisma.ParticipationUpdateWithoutContestInput, Prisma.ParticipationUncheckedUpdateWithoutContestInput>
}

export type ParticipationUpdateManyWithWhereWithoutContestInput = {
  where: Prisma.ParticipationScalarWhereInput
  data: Prisma.XOR<Prisma.ParticipationUpdateManyMutationInput, Prisma.ParticipationUncheckedUpdateManyWithoutContestInput>
}

export type ParticipationCreateWithoutAnswersInput = {
  id?: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
  user: Prisma.UserCreateNestedOneWithoutParticipationsInput
  contest: Prisma.ContestCreateNestedOneWithoutParticipationsInput
}

export type ParticipationUncheckedCreateWithoutAnswersInput = {
  id?: string
  userId: string
  contestId: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
}

export type ParticipationCreateOrConnectWithoutAnswersInput = {
  where: Prisma.ParticipationWhereUniqueInput
  create: Prisma.XOR<Prisma.ParticipationCreateWithoutAnswersInput, Prisma.ParticipationUncheckedCreateWithoutAnswersInput>
}

export type ParticipationUpsertWithoutAnswersInput = {
  update: Prisma.XOR<Prisma.ParticipationUpdateWithoutAnswersInput, Prisma.ParticipationUncheckedUpdateWithoutAnswersInput>
  create: Prisma.XOR<Prisma.ParticipationCreateWithoutAnswersInput, Prisma.ParticipationUncheckedCreateWithoutAnswersInput>
  where?: Prisma.ParticipationWhereInput
}

export type ParticipationUpdateToOneWithWhereWithoutAnswersInput = {
  where?: Prisma.ParticipationWhereInput
  data: Prisma.XOR<Prisma.ParticipationUpdateWithoutAnswersInput, Prisma.ParticipationUncheckedUpdateWithoutAnswersInput>
}

export type ParticipationUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutParticipationsNestedInput
  contest?: Prisma.ContestUpdateOneRequiredWithoutParticipationsNestedInput
}

export type ParticipationUncheckedUpdateWithoutAnswersInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ParticipationCreateManyUserInput = {
  id?: string
  contestId: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
}

export type ParticipationUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  contest?: Prisma.ContestUpdateOneRequiredWithoutParticipationsNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutParticipationNestedInput
}

export type ParticipationUncheckedUpdateWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutParticipationNestedInput
}

export type ParticipationUncheckedUpdateManyWithoutUserInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  contestId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}

export type ParticipationCreateManyContestInput = {
  id?: string
  userId: string
  status?: $Enums.ParticipationStatus
  score?: number
  startedAt?: Date | string
  submittedAt?: Date | string | null
}

export type ParticipationUpdateWithoutContestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  user?: Prisma.UserUpdateOneRequiredWithoutParticipationsNestedInput
  answers?: Prisma.AnswerUpdateManyWithoutParticipationNestedInput
}

export type ParticipationUncheckedUpdateWithoutContestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  answers?: Prisma.AnswerUncheckedUpdateManyWithoutParticipationNestedInput
}

export type ParticipationUncheckedUpdateManyWithoutContestInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  userId?: Prisma.StringFieldUpdateOperationsInput | string
  status?: Prisma.EnumParticipationStatusFieldUpdateOperationsInput | $Enums.ParticipationStatus
  score?: Prisma.IntFieldUpdateOperationsInput | number
  startedAt?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  submittedAt?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
}


/**
 * Count Type ParticipationCountOutputType
 */

export type ParticipationCountOutputType = {
  answers: number
}

export type ParticipationCountOutputTypeSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  answers?: boolean | ParticipationCountOutputTypeCountAnswersArgs
}

/**
 * ParticipationCountOutputType without action
 */
export type ParticipationCountOutputTypeDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the ParticipationCountOutputType
   */
  select?: Prisma.ParticipationCountOutputTypeSelect<ExtArgs> | null
}

/**
 * ParticipationCountOutputType without action
 */
export type ParticipationCountOutputTypeCountAnswersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.AnswerWhereInput
}


export type ParticipationSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  contestId?: boolean
  status?: boolean
  score?: boolean
  startedAt?: boolean
  submittedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.Participation$answersArgs<ExtArgs>
  _count?: boolean | Prisma.ParticipationCountOutputTypeDefaultArgs<ExtArgs>
}, ExtArgs["result"]["participation"]>

export type ParticipationSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  contestId?: boolean
  status?: boolean
  score?: boolean
  startedAt?: boolean
  submittedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["participation"]>

export type ParticipationSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  userId?: boolean
  contestId?: boolean
  status?: boolean
  score?: boolean
  startedAt?: boolean
  submittedAt?: boolean
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
}, ExtArgs["result"]["participation"]>

export type ParticipationSelectScalar = {
  id?: boolean
  userId?: boolean
  contestId?: boolean
  status?: boolean
  score?: boolean
  startedAt?: boolean
  submittedAt?: boolean
}

export type ParticipationOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "userId" | "contestId" | "status" | "score" | "startedAt" | "submittedAt", ExtArgs["result"]["participation"]>
export type ParticipationInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
  answers?: boolean | Prisma.Participation$answersArgs<ExtArgs>
  _count?: boolean | Prisma.ParticipationCountOutputTypeDefaultArgs<ExtArgs>
}
export type ParticipationIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
}
export type ParticipationIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  user?: boolean | Prisma.UserDefaultArgs<ExtArgs>
  contest?: boolean | Prisma.ContestDefaultArgs<ExtArgs>
}

export type $ParticipationPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "Participation"
  objects: {
    user: Prisma.$UserPayload<ExtArgs>
    contest: Prisma.$ContestPayload<ExtArgs>
    answers: Prisma.$AnswerPayload<ExtArgs>[]
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    userId: string
    contestId: string
    status: $Enums.ParticipationStatus
    score: number
    startedAt: Date
    submittedAt: Date | null
  }, ExtArgs["result"]["participation"]>
  composites: {}
}

export type ParticipationGetPayload<S extends boolean | null | undefined | ParticipationDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$ParticipationPayload, S>

export type ParticipationCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<ParticipationFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: ParticipationCountAggregateInputType | true
  }

export interface ParticipationDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['Participation'], meta: { name: 'Participation' } }
  /**
   * Find zero or one Participation that matches the filter.
   * @param {ParticipationFindUniqueArgs} args - Arguments to find a Participation
   * @example
   * // Get one Participation
   * const participation = await prisma.participation.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends ParticipationFindUniqueArgs>(args: Prisma.SelectSubset<T, ParticipationFindUniqueArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one Participation that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {ParticipationFindUniqueOrThrowArgs} args - Arguments to find a Participation
   * @example
   * // Get one Participation
   * const participation = await prisma.participation.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends ParticipationFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, ParticipationFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Participation that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationFindFirstArgs} args - Arguments to find a Participation
   * @example
   * // Get one Participation
   * const participation = await prisma.participation.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends ParticipationFindFirstArgs>(args?: Prisma.SelectSubset<T, ParticipationFindFirstArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first Participation that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationFindFirstOrThrowArgs} args - Arguments to find a Participation
   * @example
   * // Get one Participation
   * const participation = await prisma.participation.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends ParticipationFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, ParticipationFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more Participations that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all Participations
   * const participations = await prisma.participation.findMany()
   * 
   * // Get first 10 Participations
   * const participations = await prisma.participation.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const participationWithIdOnly = await prisma.participation.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends ParticipationFindManyArgs>(args?: Prisma.SelectSubset<T, ParticipationFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a Participation.
   * @param {ParticipationCreateArgs} args - Arguments to create a Participation.
   * @example
   * // Create one Participation
   * const Participation = await prisma.participation.create({
   *   data: {
   *     // ... data to create a Participation
   *   }
   * })
   * 
   */
  create<T extends ParticipationCreateArgs>(args: Prisma.SelectSubset<T, ParticipationCreateArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many Participations.
   * @param {ParticipationCreateManyArgs} args - Arguments to create many Participations.
   * @example
   * // Create many Participations
   * const participation = await prisma.participation.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends ParticipationCreateManyArgs>(args?: Prisma.SelectSubset<T, ParticipationCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many Participations and returns the data saved in the database.
   * @param {ParticipationCreateManyAndReturnArgs} args - Arguments to create many Participations.
   * @example
   * // Create many Participations
   * const participation = await prisma.participation.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many Participations and only return the `id`
   * const participationWithIdOnly = await prisma.participation.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends ParticipationCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, ParticipationCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a Participation.
   * @param {ParticipationDeleteArgs} args - Arguments to delete one Participation.
   * @example
   * // Delete one Participation
   * const Participation = await prisma.participation.delete({
   *   where: {
   *     // ... filter to delete one Participation
   *   }
   * })
   * 
   */
  delete<T extends ParticipationDeleteArgs>(args: Prisma.SelectSubset<T, ParticipationDeleteArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one Participation.
   * @param {ParticipationUpdateArgs} args - Arguments to update one Participation.
   * @example
   * // Update one Participation
   * const participation = await prisma.participation.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends ParticipationUpdateArgs>(args: Prisma.SelectSubset<T, ParticipationUpdateArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more Participations.
   * @param {ParticipationDeleteManyArgs} args - Arguments to filter Participations to delete.
   * @example
   * // Delete a few Participations
   * const { count } = await prisma.participation.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends ParticipationDeleteManyArgs>(args?: Prisma.SelectSubset<T, ParticipationDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Participations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many Participations
   * const participation = await prisma.participation.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends ParticipationUpdateManyArgs>(args: Prisma.SelectSubset<T, ParticipationUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more Participations and returns the data updated in the database.
   * @param {ParticipationUpdateManyAndReturnArgs} args - Arguments to update many Participations.
   * @example
   * // Update many Participations
   * const participation = await prisma.participation.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more Participations and only return the `id`
   * const participationWithIdOnly = await prisma.participation.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends ParticipationUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, ParticipationUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one Participation.
   * @param {ParticipationUpsertArgs} args - Arguments to update or create a Participation.
   * @example
   * // Update or create a Participation
   * const participation = await prisma.participation.upsert({
   *   create: {
   *     // ... data to create a Participation
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the Participation we want to update
   *   }
   * })
   */
  upsert<T extends ParticipationUpsertArgs>(args: Prisma.SelectSubset<T, ParticipationUpsertArgs<ExtArgs>>): Prisma.Prisma__ParticipationClient<runtime.Types.Result.GetResult<Prisma.$ParticipationPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of Participations.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationCountArgs} args - Arguments to filter Participations to count.
   * @example
   * // Count the number of Participations
   * const count = await prisma.participation.count({
   *   where: {
   *     // ... the filter for the Participations we want to count
   *   }
   * })
  **/
  count<T extends ParticipationCountArgs>(
    args?: Prisma.Subset<T, ParticipationCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], ParticipationCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a Participation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends ParticipationAggregateArgs>(args: Prisma.Subset<T, ParticipationAggregateArgs>): Prisma.PrismaPromise<GetParticipationAggregateType<T>>

  /**
   * Group by Participation.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {ParticipationGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends ParticipationGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: ParticipationGroupByArgs['orderBy'] }
      : { orderBy?: ParticipationGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, ParticipationGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetParticipationGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the Participation model
 */
readonly fields: ParticipationFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for Participation.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__ParticipationClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  user<T extends Prisma.UserDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.UserDefaultArgs<ExtArgs>>): Prisma.Prisma__UserClient<runtime.Types.Result.GetResult<Prisma.$UserPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  contest<T extends Prisma.ContestDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.ContestDefaultArgs<ExtArgs>>): Prisma.Prisma__ContestClient<runtime.Types.Result.GetResult<Prisma.$ContestPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  answers<T extends Prisma.Participation$answersArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.Participation$answersArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$AnswerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions> | Null>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the Participation model
 */
export interface ParticipationFieldRefs {
  readonly id: Prisma.FieldRef<"Participation", 'String'>
  readonly userId: Prisma.FieldRef<"Participation", 'String'>
  readonly contestId: Prisma.FieldRef<"Participation", 'String'>
  readonly status: Prisma.FieldRef<"Participation", 'ParticipationStatus'>
  readonly score: Prisma.FieldRef<"Participation", 'Int'>
  readonly startedAt: Prisma.FieldRef<"Participation", 'DateTime'>
  readonly submittedAt: Prisma.FieldRef<"Participation", 'DateTime'>
}
    

// Custom InputTypes
/**
 * Participation findUnique
 */
export type ParticipationFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * Filter, which Participation to fetch.
   */
  where: Prisma.ParticipationWhereUniqueInput
}

/**
 * Participation findUniqueOrThrow
 */
export type ParticipationFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * Filter, which Participation to fetch.
   */
  where: Prisma.ParticipationWhereUniqueInput
}

/**
 * Participation findFirst
 */
export type ParticipationFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * Filter, which Participation to fetch.
   */
  where?: Prisma.ParticipationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participations to fetch.
   */
  orderBy?: Prisma.ParticipationOrderByWithRelationInput | Prisma.ParticipationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Participations.
   */
  cursor?: Prisma.ParticipationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Participations.
   */
  distinct?: Prisma.ParticipationScalarFieldEnum | Prisma.ParticipationScalarFieldEnum[]
}

/**
 * Participation findFirstOrThrow
 */
export type ParticipationFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * Filter, which Participation to fetch.
   */
  where?: Prisma.ParticipationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participations to fetch.
   */
  orderBy?: Prisma.ParticipationOrderByWithRelationInput | Prisma.ParticipationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for Participations.
   */
  cursor?: Prisma.ParticipationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Participations.
   */
  distinct?: Prisma.ParticipationScalarFieldEnum | Prisma.ParticipationScalarFieldEnum[]
}

/**
 * Participation findMany
 */
export type ParticipationFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * Filter, which Participations to fetch.
   */
  where?: Prisma.ParticipationWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of Participations to fetch.
   */
  orderBy?: Prisma.ParticipationOrderByWithRelationInput | Prisma.ParticipationOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing Participations.
   */
  cursor?: Prisma.ParticipationWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` Participations from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` Participations.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of Participations.
   */
  distinct?: Prisma.ParticipationScalarFieldEnum | Prisma.ParticipationScalarFieldEnum[]
}

/**
 * Participation create
 */
export type ParticipationCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * The data needed to create a Participation.
   */
  data: Prisma.XOR<Prisma.ParticipationCreateInput, Prisma.ParticipationUncheckedCreateInput>
}

/**
 * Participation createMany
 */
export type ParticipationCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many Participations.
   */
  data: Prisma.ParticipationCreateManyInput | Prisma.ParticipationCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * Participation createManyAndReturn
 */
export type ParticipationCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * The data used to create many Participations.
   */
  data: Prisma.ParticipationCreateManyInput | Prisma.ParticipationCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * Participation update
 */
export type ParticipationUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * The data needed to update a Participation.
   */
  data: Prisma.XOR<Prisma.ParticipationUpdateInput, Prisma.ParticipationUncheckedUpdateInput>
  /**
   * Choose, which Participation to update.
   */
  where: Prisma.ParticipationWhereUniqueInput
}

/**
 * Participation updateMany
 */
export type ParticipationUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update Participations.
   */
  data: Prisma.XOR<Prisma.ParticipationUpdateManyMutationInput, Prisma.ParticipationUncheckedUpdateManyInput>
  /**
   * Filter which Participations to update
   */
  where?: Prisma.ParticipationWhereInput
  /**
   * Limit how many Participations to update.
   */
  limit?: number
}

/**
 * Participation updateManyAndReturn
 */
export type ParticipationUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * The data used to update Participations.
   */
  data: Prisma.XOR<Prisma.ParticipationUpdateManyMutationInput, Prisma.ParticipationUncheckedUpdateManyInput>
  /**
   * Filter which Participations to update
   */
  where?: Prisma.ParticipationWhereInput
  /**
   * Limit how many Participations to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * Participation upsert
 */
export type ParticipationUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * The filter to search for the Participation to update in case it exists.
   */
  where: Prisma.ParticipationWhereUniqueInput
  /**
   * In case the Participation found by the `where` argument doesn't exist, create a new Participation with this data.
   */
  create: Prisma.XOR<Prisma.ParticipationCreateInput, Prisma.ParticipationUncheckedCreateInput>
  /**
   * In case the Participation was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.ParticipationUpdateInput, Prisma.ParticipationUncheckedUpdateInput>
}

/**
 * Participation delete
 */
export type ParticipationDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
  /**
   * Filter which Participation to delete.
   */
  where: Prisma.ParticipationWhereUniqueInput
}

/**
 * Participation deleteMany
 */
export type ParticipationDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which Participations to delete
   */
  where?: Prisma.ParticipationWhereInput
  /**
   * Limit how many Participations to delete.
   */
  limit?: number
}

/**
 * Participation.answers
 */
export type Participation$answersArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Answer
   */
  select?: Prisma.AnswerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Answer
   */
  omit?: Prisma.AnswerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.AnswerInclude<ExtArgs> | null
  where?: Prisma.AnswerWhereInput
  orderBy?: Prisma.AnswerOrderByWithRelationInput | Prisma.AnswerOrderByWithRelationInput[]
  cursor?: Prisma.AnswerWhereUniqueInput
  take?: number
  skip?: number
  distinct?: Prisma.AnswerScalarFieldEnum | Prisma.AnswerScalarFieldEnum[]
}

/**
 * Participation without action
 */
export type ParticipationDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the Participation
   */
  select?: Prisma.ParticipationSelect<ExtArgs> | null
  /**
   * Omit specific fields from the Participation
   */
  omit?: Prisma.ParticipationOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.ParticipationInclude<ExtArgs> | null
}
